### ISSUE TITLE
Support Node >= 17

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Word-Addin#461]
webpack has some issues with Node 17 and 18, namely running `yarn dev-server` yields
```
$ webpack serve --mode development
You already have trusted access to https://localhost.
Certificate: /home/vscode/.office-addin-dev-certs/localhost.crt
Key: /home/vscode/.office-addin-dev-certs/localhost.key
(node:8247) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: https://localhost:3000/
<i> [webpack-dev-server] On Your Network (IPv4): https://172.16.5.4:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/workspaces/JabRef-Word-Addin/public' directory
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/workspaces/JabRef-Word-Addin/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/JabRef-Word-Addin/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/JabRef-Word-Addin/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/JabRef-Word-Addin/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/JabRef-Word-Addin/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/JabRef-Word-Addin/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/JabRef-Word-Addin/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/workspaces/JabRef-Word-Addin/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/workspaces/JabRef-Word-Addin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /workspaces/JabRef-Word-Addin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /workspaces/JabRef-Word-Addin/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.9.0
```
Skimming over https://github.com/webpack/webpack/issues/14532, updating some dependencies (react, webpack?) might fix it.

**Comment by tobiasdiez** [comment]
Fixed with #570
