### ISSUE TITLE
Make CSL processing more robust to incomplete data

### ISSUE THREAD

**Issue by koppor** [JabRef/JabRef-Word-Addin#566]
```
*** {
  "name": "SyntaxError",
  "message": "\"undefined\" is not valid JSON",
  "stack": "SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at CSL.Engine.retrieveItem (https://localhost:3000/cite.worker.worker.js:4252:17)\n    at CSL.Engine.processCitationCluster (https://localhost:3000/cite.worker.worker.js:7072:21)\n    at registerCitation (https://localhost:3000/cite.worker.worker.js:25084:32)\n    at https://localhost:3000/cite.worker.worker.js:25122:13"
```

**Comment by tobiasdiez** [comment]
Whats the context/how to reproduce this?

**Comment by koppor** [comment]
Use the branch connecting to JabRef, fire up JabRef http Server serving JabRef authors. Use the first reference there. If that works, use the second 😅
